[job]
dump_folder = "./outputs"
description = "Llama 3 405B training"

[metrics]
log_freq = 1
enable_tensorboard = false
save_tb_folder = "tb"

[model]
name = "llama3"
flavor = "405B"
hf_assets_path = "./assets/hf/Llama-3.1-405B"
converters = []

[training]
local_batch_size = 2
seq_len = 8192
max_norm = 1.0  # grad norm clipping
steps = 1000
dataset = "c4_local"
dtype = "bfloat16"
mixed_precision_reduce = "bfloat16"

[parallelism]
pipeline_parallel_degree = 1
data_parallel_replicate_degree = 2
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
enable_async_tensor_parallel = false
context_parallel_degree = 1
prefetch_before_data = true

[activation_checkpoint]
mode = "full"  # ["none", "selective", "full"]
selective_ac_option = "2"
early_stop = true

[optimizer]
name = "AdamW"
lr = 3e-4
eps = 1e-8
implementation = "fused"
early_step_in_backward = true

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 15

[compile]
enable = true
components = ["model", "loss"]

[validation]
enable = false

[checkpoint]
enable = false

[lr_scheduler]
warmup_steps = 200  # lr scheduler warm up

[infra]
set_gpu_affinity = false # FIXME
