[job]
dump_folder = "./outputs"
description = "Qwen 3 MoE debug model training"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 5
enable_tensorboard = false
save_tb_folder = "tb"

[model]
name = "qwen3"
flavor = "opt-30B-A3B"
hf_assets_path = "./assets/hf/Qwen3-30B-A3B"
# converters = ["float8"]

[optimizer]
name = "AdamW"
lr = 3e-4
eps = 1e-8
implementation = "fused"
early_step_in_backward = true

[lr_scheduler]
# DM: trying to explicitly define a decay type
warmup_steps = 200  # lr scheduler warm up, 20% total steps

[training]
# DM: Seq len = 8k and lbs = 12 has maxed out mem perfectly so far
# with selective activation checkpointing
local_batch_size = 4
seq_len = 32768
max_norm = 1.0  # grad norm clipping
steps = 1000
dataset = "c4"
dtype = "bfloat16"
mixed_precision_reduce = "bfloat16"

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = 8
# DM: Was default, switching to always
fsdp_reshard_after_forward = "default" # default / never / always
tensor_parallel_degree = 1
enable_async_tensor_parallel = false
expert_parallel_degree = 1
expert_tensor_parallel_degree = 1

[checkpoint]
enable = false
folder = "checkpoint"
interval = 10
last_save_model_only = false
export_dtype = "float16"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = "full"  # ["none", "selective", "full"]
early_stop = true
selective_ac_option = "op"  # "int" = ac every positive int layer or 'op', ac based on ops policy

[compile]
enable=true
components = ["model", "loss"]

[infra]
set_gpu_affinity = true
